default_check_interval:
  name: 'Default Check Interval'
  default: 120
  type: 'integer'

critical_check_interval:
  name: 'Critical Check Interval'
  default: 30
  type: 'integer'

request_timeout:
  name: 'Request Timeout'
  default: 20
  type: 'integer'

critical_failures_count:
  name: 'Critical failures count'
  default: 3
  type: 'integer'

repeat_notification_failures_count:
  name: 'Repeat notification after failures count'
  default: 10
  type: 'integer'
